# Generated by Django 4.0.4 on 2022-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer', 'Prefer not to say')], max_length=50)),
                ('path', models.CharField(choices=[('FullStack', 'FullStack'), ('Data', 'Data Science'), ('DevOps', 'DevOps'), ('AWS', 'AWS'), ('ITF', 'ITF')], max_length=50)),
            ],
        ),
    ]
